### ISSUE TITLE
Failed to load map! ../../../../../Users/Nutzer/Desktop/InventorySystem-master/Content/ThirdPerson/Maps/ThirdPersonMap.umap appears to be an asset file.

### ISSUE THREAD

**Issue by nIcOx05** [finalstack/InventorySystem#2]
When I want to open the project I always get the error: 
Failed to load map!
../../../../../Users/Users/Desktop/InventorySystem-master/Content/ThirdPerson/Maps/ThirdPersonMap.umap appears to be an asset file.
![Screenshot 2023-03-11 214713](https://user-images.githubusercontent.com/127629521/224510916-aba83b53-9cb9-405c-8678-449ee33ddd31.png)

**Comment by finalstack** [comment]
Hi there,
- Download and install Git client https://git-scm.com/
- Download and install Git LFS https://git-lfs.com/
- Run this command in the terminal: ``git lfs install``
- Clone the repo and try again.
