### ISSUE TITLE
Only the very edge of hotbar can be the drag location

### ISSUE THREAD

**Issue by DalKoe** [finalstack/InventorySystem#3]
1: Cloned fresh inventory system
2: Set the player controller to be the inventory system one
3: Added the interface pickup to the player character BP
4: Pickup an item
5: Attempt to drag it to the inventory

It doesnt allow me to select the slot by hovering the mouse over the image of the hotbar, i have to put the mouse at the very edge around the image on the actual button to be able to drag it. 

Trying to drag the actual item image just moves the camera. 

The drag and drop works perfectly in the inventory itself just not the hotbar

**Comment by finalstack** [comment]
The same drag and drop logic is implemented for Hotbar and Inventory, so technically it should work for both!

Can you upload a demo video or animated GIF?

**Comment by DalKoe** [comment]
https://streamable.com/0bomgx

Here is a fresh download, migrated to my project. Set the player controller and this is the result. Only detects the very edge of the slot

**Comment by finalstack** [comment]
I think it is something to do with the Visibility setting in the widgets, what is your UE version?

**Comment by DalKoe** [comment]
> I think it is something to do with the Visibility setting in the widgets, what is your UE version?

5.1.1
